### ISSUE TITLE
Error on pip install (Red Hat Linux)

### ISSUE THREAD

**Issue by hemmelig** [scikit-fmm/scikit-fmm#39] opened 2020-06-16 13:36 UTC
Hi,

`scikit-fmm` is one of the dependencies of our project (https://github.com/QuakeMigrate/QuakeMigrate). We have had reports from a user that they are getting the following error when installing:

```
Collecting scikit-fmm
  Downloading scikit-fmm-2019.1.30.tar.gz (418 kB)
     |████████████████████████████████| 418 kB 381 kB/s
Requirement already satisfied: numpy>=1.0.2 in /share/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages (from scikit-fmm) (1.17.3)
Building wheels for collected packages: scikit-fmm
  Building wheel for scikit-fmm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mfsx4cs8/scikit-fmm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mfsx4cs8/scikit-fmm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-14799q9q
       cwd: /tmp/pip-install-mfsx4cs8/scikit-fmm/
  Complete output (47 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "skfmm.cfmm" sources
  building extension "skfmm.pheap" sources
  build_src: building npy-pkg config files
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/setup.py -> build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/__init__.py -> build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/heap.py -> build/lib.linux-x86_64-3.8/skfmm
  copying skfmm/pfmm.py -> build/lib.linux-x86_64-3.8/skfmm
  running build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  building 'skfmm.cfmm' extension
  compiling C++ sources
  C compiler: g++ -pthread -B /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC  creating build/temp.linux-x86_64-3.8/skfmm
  compile options: '-Iskfmm -I/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include -I/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/include/python3.8 -c'
  g++: skfmm/fmm.cppg++: skfmm/heap.cpp
  g++: skfmm/base_marcher.cpp  g++: skfmm/travel_time_marcher.cpp
  g++: skfmm/distance_marcher.cppg++: skfmm/extension_velocity_marcher.cpp  In file included from /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                   from /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/noprefix.h:9,
                   from skfmm/fmm.cpp:5:
  /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^
  g++ -pthread -shared -B /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/compiler_compat -L/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,-rpath=/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/skfmm/fmm.o build/temp.linux-x86_64-3.8/skfmm/heap.o build/temp.linux-x86_64-3.8/skfmm/base_marcher.o build/temp.linux-x86_64-3.8/skfmm/distance_marcher.o build/temp.linux-x86_64-3.8/skfmm/travel_time_marcher.o build/temp.linux-x86_64-3.8/skfmm/extension_velocity_marcher.o -o build/lib.linux-x86_64-3.8/skfmm/cfmm.cpython-38-x86_64-linux-gnu.so
  /usr/bin/ld: this linker was not configured to use sysroots
  collect2: error: ld returned 1 exit status
  error: Command "g++ -pthread -shared -B /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/compiler_compat -L/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,-rpath=/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/skfmm/fmm.o build/temp.linux-x86_64-3.8/skfmm/heap.o build/temp.linux-x86_64-3.8/skfmm/base_marcher.o build/temp.linux-x86_64-3.8/skfmm/distance_marcher.o build/temp.linux-x86_64-3.8/skfmm/travel_time_marcher.o build/temp.linux-x86_64-3.8/skfmm/extension_velocity_marcher.o -o build/lib.linux-x86_64-3.8/skfmm/cfmm.cpython-38-x86_64-linux-gnu.so" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scikit-fmm
  Running setup.py clean for scikit-fmm
Failed to build scikit-fmm
Installing collected packages: scikit-fmm
    Running setup.py install for scikit-fmm ... error
    ERROR: Command errored out with exit status 1:
     command: /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mfsx4cs8/scikit-fmm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mfsx4cs8/scikit-fmm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j3p8l5f2/install-record.txt --single-version-externally-managed --compile --install-headers /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/include/python3.8/scikit-fmm
         cwd: /tmp/pip-install-mfsx4cs8/scikit-fmm/
    Complete output (43 lines):                Note: if you need to uninstall you should `pip install scikit-fmm` instead of using `setup.py install`    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "skfmm.cfmm" sources
    building extension "skfmm.pheap" sources
    build_src: building npy-pkg config files
    running build_py
    running build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    building 'skfmm.cfmm' extension
    compiling C++ sources
    C compiler: g++ -pthread -B /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC    creating build/temp.linux-x86_64-3.8/skfmm
    compile options: '-Iskfmm -I/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include -I/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/include/python3.8 -c'
    g++: skfmm/fmm.cpp
    g++: skfmm/distance_marcher.cpp
    g++: skfmm/travel_time_marcher.cpp
    g++: skfmm/base_marcher.cpp
    g++: skfmm/extension_velocity_marcher.cpp
    g++: skfmm/heap.cpp
    In file included from /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                     from /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/noprefix.h:9,
                     from skfmm/fmm.cpp:5:
    /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^
    g++ -pthread -shared -B /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/compiler_compat -L/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,-rpath=/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/skfmm/fmm.o build/temp.linux-x86_64-3.8/skfmm/heap.o build/temp.linux-x86_64-3.8/skfmm/base_marcher.o build/temp.linux-x86_64-3.8/skfmm/distance_marcher.o build/temp.linux-x86_64-3.8/skfmm/travel_time_marcher.o build/temp.linux-x86_64-3.8/skfmm/extension_velocity_marcher.o -o build/lib.linux-x86_64-3.8/skfmm/cfmm.cpython-38-x86_64-linux-gnu.so
    /usr/bin/ld: this linker was not configured to use sysroots
    collect2: error: ld returned 1 exit status
    error: Command "g++ -pthread -shared -B /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/compiler_compat -L/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,-rpath=/home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/skfmm/fmm.o build/temp.linux-x86_64-3.8/skfmm/heap.o build/temp.linux-x86_64-3.8/skfmm/base_marcher.o build/temp.linux-x86_64-3.8/skfmm/distance_marcher.o build/temp.linux-x86_64-3.8/skfmm/travel_time_marcher.o build/temp.linux-x86_64-3.8/skfmm/extension_velocity_marcher.o -o build/lib.linux-x86_64-3.8/skfmm/cfmm.cpython-38-x86_64-linux-gnu.so" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mfsx4cs8/scikit-fmm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mfsx4cs8/scikit-fmm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j3p8l5f2/install-record.txt --single-version-externally-managed --compile --install-headers /home1/-/Tools/Anaconda/anaconda/envs/QuakeMigrate/include/python3.8/scikit-fmm Check the logs for full command output.
``` 

This error only occurs when installing from this yml:
```
name: QuakeMigrate
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg
  - ipython
  - jupyter
  - numpy
  - obspy
  - pandas
  - pip
  - python
  - pyproj
  - scipy
  - pip:
    - scikit-fmm==2019.1.30
```
There is no error when installing from:
```
name: QuakeMigrate
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=3.4.1*=2
  - ipython
  - jupyter
  - libgcc-ng
  - matplotlib
  - numpy
  - obspy
  - pandas=0.19.*
  - pip
  - pyqt
  - python
  - scipy
  - pyproj
  - pip:
    - cython==0.24.1
    - scikit-fmm==2019.1.30
```

The operating system is Red Hat Enterprise Linux.

However, I am unable to replicate the issue. Installing on my Ubuntu 18.04 works completely fine. Let me know if you need any more information and I can try get it.

Thanks!

**Comment by jkfurtney** [comment] 2020-06-16 13:43
Hmm, Sorry I am not much help on this one. There is a warning message from the NumPy API, but I do not think that is causing the problem (unless maybe the compiler treat warnings as errors setting is on, but that does not seem to be the case). It looks like the linker is failing for some reason.

**Comment by jkfurtney** [comment] 2021-02-02 21:59
This may be fixed by the latest release (2021.2.2)? The latest release fixes some issue with building via pip.

**Comment by jkfurtney** [comment] 2021-02-02 22:00
Can someone try to reproduce this problem with the latest version please? I do not have a Red Hat system.

**Comment by ypp2020** [comment] 2023-10-13 02:07
maybe you can choose conda install ? i sucessfully installed  by this command. but this command change my python version from 3.8 to 3.11

**Comment by jkfurtney** [comment] 2023-10-16 17:27
OK, I am going to close this issue. If there is still a problem, please re-open with a comment.

**Closed by jkfurtney** 2023-10-16 17:27 UTC
